spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school_db
    username: admin
    password: admin
  jpa:
    show-sql: false

server:
  port: 2022